[package]
name = "print-guid"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
is-root = "0.1.3"
windows = { version = "0.58.0", features = [
  "Win32_Devices_DeviceAndDriverInstallation",
] }
