[package]
name = "print-guid"
version = "0.1.1"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
windows = { version = "0.62.2", features = [
  "Win32_Devices_DeviceAndDriverInstallation",
  "Win32_Security",
  "Win32_System",
  "Win32_System_Threading"
] }
